### ISSUE TITLE
flinger framebuffer copier shouldnt copy buffers if stride is 0

### ISSUE THREAD

**Issue by filmaj** [filmaj/droid-VNC-server#4]

**Comment by mhan** [comment]
Fixed in 9f65edaeee0d400269322c5efaad2d4c1f9a81cb

Just for clarification, I was wrong when I reported the stride length as 0 on the Nexus 4. It was actually 768 which matches the width. So when stride == width, it denotes the image is in a contiguous block in memory and its this case where we want to avoid doing the buffer copy.
